name: CBM101
dependencies:
- python>=3.6.0
- ipython
- ipywidgets
- jupyter
- git
- numpy=1.21
- matplotlib
- pandas
- scikit-learn
- ipykernel
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- conda-forge::statsmodels
- conda-forge::biopython
- conda-forge::graphviz
- conda-forge::nxviz
- conda-forge::umap-learn
- conda-forge::opencv
- conda-forge::pandas-profiling
- conda-forge::geoparse
- scipy
- seaborn
- imageio
- simplegeneric
- pytables
- openpyxl
- basemap
- scikit-image
- networkx
- xlrd
- plotly